services:
  master:
    container_name: mysql-master
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 3306:3306
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
    networks:
      - mysql_network

  slave:
    container_name: mysql-slave
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 3307:3306
    volumes:
      - ./slave.cnf:/etc/mysql/conf.d/slave.cnf
    command: --server-id=2 --gtid-mode=ON --enforce-gtid-consistency=ON
    networks:
      - mysql_network

networks:
  mysql_network: