services:
  postgresql1:
    container_name: postgresql_master
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test_db
    networks:
      - postgresql_network

  postgresql2:
    container_name: postgresql_repl
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test_db
    networks:
      - postgresql_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_ALLOW_WHITELIST_SOURCE_RANGES: '["192.168.0.0/24"]'
    ports:
      - "5050:80"
    depends_on:
      - postgresql1
    networks:
      postgresql_network:

networks:
  postgresql_network:
    driver: bridge
